# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Deploy package

on:
  push:
    branches: ['main']
jobs:
  build:
    name: Build lib
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npm test 
  publish-npm:
    name: NPM Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
      - uses: actions/checkout@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  # release:
  #   name: Github Release
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Release
  #       uses: fdiesel/github-action-node-release@v4.1.5
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}
  #         prefix: v # (optional) default none
